package eu.nicosworld.rithmo.core.turn.option;

/**
 * Root interface representing a legal choice presented to the player during a turn.
 * <p>
 * TurnOptions are generated by the {@link eu.nicosworld.rithmo.core.turn.resolver.PhaseResolver}
 * and intended to be displayed by the UI. Once selected, an option is usually
 * converted into a {@link eu.nicosworld.rithmo.core.turn.action.TurnAction}.
 */
public sealed interface TurnOption
        permits PreCaptureOption,
        SkipPreCaptureOption,
        MoveOption,
        PostCaptureOption,
        SkipPostCaptureOption {
}