package eu.nicosworld.rithmo.core.turn.option;

/**
 * Root interface representing a legal player choice produced by the engine during a turn.
 *
 * <p>{@code TurnOption}s are generated by the {@link
 * eu.nicosworld.rithmo.core.turn.resolver.PhaseResolver} during phase computation.
 *
 * <p>They act as application-facing projection inputs and are later transformed into:
 *
 * <ul>
 *   <li>player-visible option DTOs
 *   <li>UI decisions
 *   <li>executable {@link eu.nicosworld.rithmo.core.turn.action.TurnAction}s
 * </ul>
 *
 * <p>Each implementation represents a specific type of legal interaction available during the
 * current turn phase.
 */
public sealed interface TurnOption
    permits MoveOption,
        PostCaptureOption,
        PreCaptureOption,
        ReintroductionOption,
        SkipPostCaptureOption,
        SkipPreCaptureOption {}
